### PR TITLE
[Network] Prevent the visitors from selecting the same main intervention multiple times in the project form

### PR DESCRIPTION
**Pull request by clementprdhomme**
This PR prevents the visitors from selecting the same main intervention multiple times in the project form.

## Acceptance criteria

- The visitor is unable to select the same area of intervention multiple times in the fields “Main area of intervention”, “Secondary area of intervention” and “Third area of intervention” in the project form
  - Options already selected in another field are disabled

## Tracking

[ORC-404](https://vizzuality.atlassian.net/browse/ORC-404)

[ORC-404]: https://vizzuality.atlassian.net/browse/ORC-404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by Bluesmile82** [comment]
Can you test sending a project to the API? In my computer is failing with a 500

**Comment by clementprdhomme** [comment]
I've identified that the 500 error is due to a recent back-end change: https://vizzuality.atlassian.net/browse/ORC-410?focusedCommentId=27975.

Let's wait until it's fixed before reviewing this PR again.

**Comment by clementprdhomme** [comment]
@Bluesmile82 This can be reviewed again. The back-end bug has been fixed.

**Review by Bluesmile82 — APPROVED** [review]
Thanks!

**Pull request merged**
